export const bgColor = 'white'
export const defaultColor = '#CCC'
export const btnPrimary = '#3f51b5'
export const btnWarning = '#F93'
export const btnSuccess = '#0A0'
export const btnDanger = '#C33'
